# Generated by Django 4.0.1 on 2022-02-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_executive',
            field=models.BooleanField(default=False, help_text='Designates that this user is part of the executive committee.', verbose_name='executive status'),
        ),
    ]
