# Generated by Django 4.0.1 on 2022-02-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_is_executive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='second_section',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
