# Generated by Django 4.1.2 on 2022-11-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_second_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_permission',
            field=models.BooleanField(default=False, verbose_name='photographic permission'),
        ),
    ]
