# Generated by Django 4.0.1 on 2022-02-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_second_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='second_section',
        ),
    ]
