# Generated by Django 4.1.2 on 2022-11-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_photo_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_permission',
            field=models.CharField(max_length=5, verbose_name='photographic permission'),
        ),
    ]
