# Generated by Django 4.0.1 on 2022-02-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.CharField(max_length=30),
        ),
    ]
