# Generated by Django 4.1.3 on 2022-11-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_photo_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='Dark', help_text='Please select your theme, dark mode or light mode.', max_length=20, verbose_name='theme'),
        ),
    ]
