# Generated by Django 4.1.3 on 2022-11-23 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme')], help_text='Please select your theme, dark mode or light mode.', max_length=20, verbose_name='theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='preferences',
            constraint=models.UniqueConstraint(fields=('user',), name='One Entry Per User'),
        ),
    ]
