# Generated by Django 4.0.1 on 2022-02-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.CharField(max_length=30),
        ),
    ]
