# Generated by Django 4.1.3 on 2022-11-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_theme_preferences_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
