# Generated by Django 4.1.3 on 2022-11-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_delete_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='Dark', help_text='Please select your colour theme.', max_length=20, verbose_name='theme'),
        ),
    ]
