# Generated by Django 3.2.5 on 2021-07-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0003_auto_20210705_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/scouts/%Y/%B/'),
        ),
    ]
