# Generated by Django 3.2.5 on 2021-07-30 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scouts', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='scouts_blog_posts_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
