# Generated by Django 3.2.5 on 2021-09-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubs', '0003_auto_20210730_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PostImage',
        ),
    ]
