# Generated by Django 4.1.3 on 2022-11-24 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cubs', '0005_auto_20210906_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='cubs_blog_posts_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
