# Generated by Django 4.1.3 on 2023-01-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubs', '0007_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[('D', 'Draft'), ('P', 'Published')], default='D'),
        ),
    ]
