# Generated by Django 3.1.4 on 2020-12-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0003_auto_20201228_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='waitinglist',
            options={'verbose_name': 'Waiting List Entry', 'verbose_name_plural': 'Waiting List Entries'},
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='parent_carer_email',
            field=models.EmailField(max_length=254, verbose_name='email of parent/carer'),
        ),
    ]
