# Generated by Django 3.2.5 on 2021-08-22 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_website', '0008_auto_20210705_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Group Event', 'verbose_name_plural': 'Group Events'},
        ),
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name': 'Image Gallery', 'verbose_name_plural': 'Image Galleries'},
        ),
        migrations.AlterModelOptions(
            name='waitinglist',
            options={'verbose_name': 'Waiting List Submission', 'verbose_name_plural': 'Waiting List Submissions'},
        ),
        migrations.CreateModel(
            name='UrgentAnnouncements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
