# Generated by Django 3.2.5 on 2021-08-29 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_website', '0009_auto_20210822_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name': 'Image Gallery', 'verbose_name_plural': 'Image Gallery'},
        ),
        migrations.AlterModelOptions(
            name='urgentannouncements',
            options={'verbose_name': 'Urgent Announcement', 'verbose_name_plural': 'Urgent Announcements'},
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='file_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ImageGalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Category',
                'verbose_name_plural': 'Image Categories',
            },
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_website.imagegallerycategory'),
        ),
    ]
