# Generated by Django 3.2.5 on 2021-09-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0010_auto_20210829_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Image Gallery'},
        ),
        migrations.AlterModelOptions(
            name='imagegallerycategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Image Categories'},
        ),
        migrations.AlterModelOptions(
            name='urgentannouncements',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Urgent Announcements'},
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to='media/image_gallery/<django.db.models.fields.related.ForeignKey>/%Y/%B/'),
        ),
    ]
