# Generated by Django 3.2.5 on 2021-09-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0011_auto_20210903_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to='media/image_gallery/%Y/%B/'),
        ),
    ]
