# Generated by Django 3.2.5 on 2021-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0012_alter_imagegallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='section_of_interest',
            field=models.IntegerField(choices=[(0, 'Beavers'), (1, 'Cubs'), (2, 'Scouts'), (3, 'Unsure Of Section')], default=3, help_text='Section that your child wants to join'),
        ),
    ]
