# Generated by Django 3.2.5 on 2021-09-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0013_alter_waitinglist_section_of_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to='image_gallery/%Y/%B/'),
        ),
    ]
