# Generated by Django 3.2.5 on 2021-09-04 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_website', '0014_alter_imagegallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_website.imagegallerycategory'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to='media/image_gallery/%Y/%B/'),
        ),
        migrations.AlterField(
            model_name='imagegallerycategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
