# Generated by Django 4.1.3 on 2022-11-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0016_imagegallery_date_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='section_of_interest',
            field=models.CharField(help_text='Section that your child wants to join', max_length=30),
        ),
    ]
