# Generated by Django 4.1.3 on 2022-11-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0017_alter_waitinglist_section_of_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(help_text='Decide whether you want to Publish the news article or save it as a Draft', max_length=10),
        ),
    ]
