# Generated by Django 4.1.3 on 2023-01-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0021_remove_imagegallery_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallerycategory',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImageGallery',
        ),
        migrations.DeleteModel(
            name='ImageGalleryCategory',
        ),
    ]
