# Generated by Django 3.1.4 on 2021-01-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quartermastersiteminventory',
            old_name='content',
            new_name='notes',
        ),
    ]
