# Generated by Django 3.1.4 on 2021-01-16 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0002_auto_20210116_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quartermastersiteminventory',
            options={'verbose_name': 'Quartermasters Item Inventory', 'verbose_name_plural': 'Quartermasters Item Inventory'},
        ),
        migrations.AddField(
            model_name='quartermastersiteminventory',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
