# Generated by Django 3.1.4 on 2021-01-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0003_auto_20210116_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quartermastersiteminventory',
            options={},
        ),
    ]
