# Generated by Django 3.1.4 on 2021-01-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0005_auto_20210118_1214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='QuartermastersItemInventory',
        ),
        migrations.AlterModelOptions(
            name='quartermastersiteminventory',
            options={'verbose_name': 'Quartermasters Item Inventory', 'verbose_name_plural': 'Quartermasters Item Inventory'},
        ),
    ]
