# Generated by Django 3.1.4 on 2021-01-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0006_auto_20210118_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quartermastersiteminventory',
            options={'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AlterField(
            model_name='quartermastersiteminventory',
            name='category',
            field=models.IntegerField(choices=[('Unspecified', 'Unspecified'), ('Camp Equipment', 'Camp Equipment'), ('Sports Equipment', 'Sports Equipment'), ('Cooking Equipment', 'Cooking Equipment'), ('General Equipment', 'General Equipment')], default=0, help_text='Category of item'),
        ),
    ]
