# Generated by Django 3.1.4 on 2021-01-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0007_auto_20210125_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartermastersiteminventory',
            name='category',
            field=models.CharField(choices=[('Unspecified', 'Unspecified'), ('Camp Equipment', 'Camp Equipment'), ('Sports Equipment', 'Sports Equipment'), ('Cooking Equipment', 'Cooking Equipment'), ('General Equipment', 'General Equipment')], default=0, help_text='Category of item', max_length=200),
        ),
    ]
