# Generated by Django 3.2.5 on 2021-07-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0008_auto_20210125_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartermastersiteminventory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
