# Generated by Django 3.2.5 on 2021-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0009_alter_quartermastersiteminventory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartermastersiteminventory',
            name='category',
            field=models.CharField(choices=[('U', 'Unspecified'), ('CAE', 'Camp Equipment'), ('SE', 'Sports Equipment'), ('COE', 'Cooking Equipment'), ('GE', 'General Equipment')], default='U', help_text='Category of item', max_length=200),
        ),
        migrations.AlterField(
            model_name='quartermastersiteminventory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
