# Generated by Django 3.2.5 on 2021-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0010_auto_20210903_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartermastersiteminventory',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
