# Generated by Django 4.0.1 on 2022-02-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0011_alter_quartermastersiteminventory_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartermastersiteminventory',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quartermastersiteminventory',
            name='category',
            field=models.CharField(choices=[('Unspecified', 'Unspecified'), ('Camp Equipment', 'Camp Equipment'), ('Sports Equipment', 'Sports Equipment'), ('Cooking Equipment', 'Cooking Equipment'), ('General Equipment', 'General Equipment')], default='Unspecified', help_text='Category of item', max_length=200),
        ),
    ]
